module.exports = {
    "RECIPE_EN_GB" : {
        "baked apple" : "you need an apple, and you will get three quarter hearts for it",
        "baked palm fruit": "you need a palm fruit, and you will get half a heart for it",
        "fish and mushroom skewer": "you need fleet-lotus seeds, a zapshroom and a staminoka bass. You will get 7 hearts for it",
        "dubious food": "you will get one heart for this, and to cook it you need random ingredients",
        "fish skewer" : "you will need a hyrule bass, and for this you will get two hearts",
        "fried egg and rice" : "you will need hylian rice and a bird egg, and this will get you four hearts",
        "fruit and mushroom mix": "you will get two hearts for this, you need an apple and a hylian shroom",
        "fried wild greens": "you will need raw meat, hyrule herbs, a swift carrot, and spicy peppers. You will get 8 hearts",
        "glazed meat": "you need a hearty truffle, some raw meat, a courser bee and some honey. you'll get 10 hearts for it.",
        "honeyed fruits": "a courser bee, some honey and a spicy pepper are required to get the five hearts from this recipie.",
        "meat and mushroom skewer": "you need raw meat or bird meat and a hylian shroom. This is worth three hearts.",
        "meat and seafood fry": "you need raw meat, a mighty carp, and some spicy peppers. This gets you eight hearts.",
        "meat skewer": "you get two hearts and you only need raw bird and a drumstick",
        "meaty rice balls": "you get four hearts for this when you cook some raw meat and hylian rice.",
        "omlet": "you can get two hearts from this with just one bird egg, or you can get more hearts for each omlet you put in the pot.",
        "pepper steak": "for a spicy pepper, a mighty thistle, a raw bird and a drumstick, you get three hearts.",
        "roasted acorn": "for an acorn, you'll get a half heart.",
        "roasted bird drumstick": "you'll get a single heart and an extra half for a raw bird drumstick.",
        "roasted radish": "you'll get a three and three quarter hearts for a hearty radish.",
        "roasted bass": "One and a half hearts can be yours, for just one hyrule bass.",
        "salt-grilled meat": "Raw meat, Raw Bird, a drumstick and some rock salt will get you two hearts when cooked.",
        "salt-grilled mushrooms": "One heart is all you'll get for a hylian shroom and some rock salt, call this a last resort.",
        "seared gourmet steak": "four and a half hearts is yours for some raw gourmet meat",
        "seared prime steak": "two hearts is what you'll get for some raw prime meat",
        "simmered fruit": "apples, acorns, or spicy peppers can all be used to get your one heart.",
        "steak skewer": "two hearts can be yours, all for a seared steak, which itself is a cooked raw meat.",
        "steamed meat": "you need raw meat, and will get 11 hearts, wow!",
        "steamed mushrooms": "Stamella shrooms and blue nightshade are what you'll need for two hearts.",
        "toasty hylian shroom": "One and a half hearts is available here for a hylian shroom.",
        "toasty stamella shroom": "One and a half hearts is available here for a stamella shroom."
        },
    "RECIPE_EN_US" : {
                "baked apple" : "you need an apple, and you will get three quarter hearts for it",
        "baked palm fruit": "you need a palm fruit, and you will get half a heart for it",
        "fish and mushroom skewer": "you need fleet-lotus seeds, a zapshroom and a staminoka bass. You will get 7 hearts for it",
        "dubious food": "you will get one heart for this, and to cook it you need random ingredients",
        "fish skewer" : "you will need a hyrule bass, and for this you will get two hearts",
        "fried egg and rice" : "you will need hylian rice and a bird egg, and this will get you four hearts",
        "fruit and mushroom mix": "you will get two hearts for this, you need an apple and a hylian shroom",
        "fried wild greens": "you will need raw meat, hyrule herbs, a swift carrot, and spicy peppers. You will get 8 hearts",
        "glazed meat": "you need a hearty truffle, some raw meat, a courser bee and some honey. you'll get 10 hearts for it.",
        "honeyed fruits": "a courser bee, some honey and a spicy pepper are required to get the five hearts from this recipie.",
        "meat and mushroom skewer": "you need raw meat or bird meat and a hylian shroom. This is worth three hearts.",
        "meat and seafood fry": "you need raw meat, a mighty carp, and some spicy peppers. This gets you eight hearts.",
        "meat skewer": "you get two hearts and you only need raw bird and a drumstick",
        "meaty rice balls": "you get four hearts for this when you cook some raw meat and hylian rice.",
        "omlet": "you can get two hearts from this with just one bird egg, or you can get more hearts for each omlet you put in the pot.",
        "pepper steak": "for a spicy pepper, a mighty thistle, a raw bird and a drumstick, you get three hearts.",
        "roasted acorn": "for an acorn, you'll get a half heart.",
        "roasted bird drumstick": "you'll get a single heart and an extra half for a raw bird drumstick.",
        "roasted radish": "you'll get a three and three quarter hearts for a hearty radish.",
        "roasted bass": "One and a half hearts can be yours, for just one hyrule bass.",
        "salt-grilled meat": "Raw meat, Raw Bird, a drumstick and some rock salt will get you two hearts when cooked.",
        "salt-grilled mushrooms": "One heart is all you'll get for a hylian shroom and some rock salt, call this a last resort.",
        "seared gourmet steak": "four and a half hearts is yours for some raw gourmet meat",
        "seared prime steak": "two hearts is what you'll get for some raw prime meat",
        "simmered fruit": "apples, acorns, or spicy peppers can all be used to get your one heart.",
        "steak skewer": "two hearts can be yours, all for a seared steak, which itself is a cooked raw meat.",
        "steamed meat": "you need raw meat, and will get 11 hearts, wow!",
        "steamed mushrooms": "Stamella shrooms and blue nightshade are what you'll need for two hearts.",
        "toasty hylian shroom": "One and a half hearts is available here for a hylian shroom.",
        "toasty stamella shroom": "One and a half hearts is available here for a stamella shroom."
    }
};